# General Settings
title: Rusty Magnet
email: rustymagnet3000@gmail.com
baseurl: ""
url: ""
github_username: rustymagnet3000
author: rustymagnet3000@gmail.com

# Build settings
theme: jekyll-theme-minimal
markdown: kramdown